# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [27]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
vac_df = pd.read_csv("../output_data/Marks_cities.csv")
vac_df.head()

,City,Country,Date,Max Temp,Humidity,Cloudiness,Wind Speed,Lat,Lng
0,Busselton,AU,1587418253,15.00,68,18,4.69,-33.65,115.33
1,Ushuaia,AR,1587417835,6.00,87,75,18.50,-54.80,-68.30
2,Vanimo,PG,1587418534,26.28,82,99,3.01,-2.67,141.30
3,Turaif,SA,1587418535,20.00,37,0,4.10,31.67,38.66
4,Kavieng,PG,1587418535,29.02,71,73,0.24,-2.57,150.80

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)
locations = vac_df[["Lat", "Lng"]].astype(float)
humidity = vac_df["Humidity"].astype(float)
fig = gmaps.figure(center=(0,0), zoom_level=2)
max_humid = vac_df["Humidity"].max()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max_humid,
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
vac_df_F = vac_df.copy()
vac_df_F['Max Temp'] = vac_df_F['Max Temp'] * 9/5 + 32
ideal_df = vac_df_F[vac_df_F['Max Temp'] <= 80]
ideal_df = ideal_df[ideal_df['Max Temp'] >= 65]
ideal_df = ideal_df[ideal_df['Humidity'] <= 55]
ideal_df = ideal_df[ideal_df['Cloudiness'] <= 7]
ideal_df = ideal_df[ideal_df['Wind Speed'] <= 8]

,City,Country,Date,Max Temp,Humidity,Cloudiness,Wind Speed,Lat,Lng
3,Turaif,SA,1587418535,68.000,37,0,4.10,31.67,38.66
20,Wadd훮n,LY,1587418539,79.790,15,0,4.89,29.16,16.14
129,R훮wah,IQ,1587418573,75.344,29,2,2.47,34.48,41.91
167,Baker City,US,1587418586,69.800,22,1,1.50,44.77,-117.83
185,Sabha,LY,1587418590,79.124,19,0,4.55,27.04,14.43
227,N훮l큰t,LY,1587418594,69.458,31,0,4.72,30.33,10.85
246,Duncan,US,1587418610,75.002,49,1,2.64,34.50,-97.96
271,S찾o Luiz Gonzaga,BR,1587418618,74.444,42,0,1.88,-28.41,-54.96
368,Santa Maria,BR,1587418651,71.564,53,0,1.04,-29.68,-53.81
386,Asw훮n,EG,1587418654,76.982,23,6,3.71,24.09,32.91
439,Saint George,US,1587418674,75.002,28,1,2.59,37.10,-113.58
440,Artigas,UY,1587418674,75.344,45,0,0.40,-30.40,-56.47
456,San Vicente,AR,1587418682,70.754,45,0,0.72,-26.62,-54.13
463,Salamiyah,SY,1587418686,65.534,52,7,0.78,35.01,37.05
533,Baharly,TM,1587418719,73.490,28,0,3.53,38.44,57.43

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [59]:
narrowed_city_df = ideal_df.copy()
narrowed_city_df = narrowed_city_df.reset_index()
narrowed_city_df = narrowed_city_df.drop(['index'], axis=1)
narrowed_city_df['Hotel Name'] = ""


hotel_name = []
target_radius = 5000
target_type = "lodging"
target_search = "Hotel"
x = 0

for row in narrowed_city_df.itertuples() :
    row_lat = row.Lat
    row_lng = row.Lng
    target_coordinates = str(row_lat) + "," + str(row_lng)
    params = {
        "location": target_coordinates,
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }

    # base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # run a request using our params dictionary
    response = requests.get(base_url, params=params)
    hotel_data = response.json()
    if (hotel_data["results"][0]["name"]) != None :
        hotel_name = hotel_data["results"][0]["name"]
    else:
        hotel_name = "None"
    
    print(hotel_name)

31.67,38.66
Golden Dune Hotel
29.16,16.14

IndexError: list index out of range

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

KeyError: 'Hotel Name'

In [ ]:
# Add marker layer ontop of heat map


# Display Map